### ISSUE TITLE
Signed 32-bit integer documentation is unclear

### ISSUE THREAD

**Issue by oschwald** [maxmind/MaxMind-DB#12]
Currently the docs state, "When storing a signed integer, the left-most bit is the sign. A 1 is negative and a 0 is positive." However, I believe this is only true if the size is 4 bytes, at least going by all of our implementations. For example, if the stored size of the int32 is 1 byte, we treat `10000001` as 129 rather than -127.

**Comment by bbkr** [comment]
Also there is no information that it means two's complement format. I felt into this trap and applied current description literally at the beginning - `0b1000001 == -1`.
