### ISSUE TITLE
Possibility to generate testing database instead of using downloaded binary files

### ISSUE THREAD

**Issue by nezdolik** [maxmind/MaxMind-DB#121]
Hi, is there is a way/tool/api to generate testing databases in mmdb format based on a given input? Asking in context of adding [Maxmind support](https://github.com/envoyproxy/envoy/pull/28490/files#r1341703827) to Envoy geolocation filter, where we have to check in testing binary databases from this repo and is not the most optimal approach from security and code readability standpoints.

**Comment by oschwald** [comment]
These files are generated from the data in the `source-data` directory using [the script `test-data/write-test-data.pl`](https://github.com/maxmind/MaxMind-DB/blob/main/test-data/write-test-data.pl).

If you want to write your own databases with custom values, I would suggest using [the Go `mmdbwriter`](https://github.com/maxmind/mmdbwriter). It is likely that the Perl writer code used by this repo will be deprecated in the near future.

**Comment by nezdolik** [comment]
Thank you @oschwald for fast response!
