### ISSUE TITLE
How to obtain testfiles for CI without running into licensing issues?

### ISSUE THREAD

**Issue by unilynx** [maxmind/MaxMind-DB#129]
Is it okay to copy the files test-data/GeoLite2-City-Test.mmdb and test-data/GeoLite2-Country-Test.mmdb into other (MIT licensed) projects ? The CC-BY-SA 3.0 license on this repository seems to forbid it (as I understand the license, it would be viral)

If not, are these or similar testdata files available somewhere  ? (so we can avoid our CI builders from hitting the download limits)

**Comment by oschwald** [comment]
Thanks for raising this. The CC license was originally intended for the specification and we didn't reconsider it once we started adding the test databases and associated code. We have change the license to the Apache License, Version 2.0, or the MIT license, at your choice. This matches what we do for most of our other projects. Hopefully this is suitable to your use case.
