### ISSUE TITLE
16 bytes IEEE754 - bug or undocumented feature?

### ISSUE THREAD

**Issue by bbkr** [maxmind/MaxMind-DB#146]
Hi

I'm maintainer of Raku library for MaxMind databases. I got [report that 16 bytes IEEE754 was spotted ](https://github.com/bbkr/GeoIP2/issues/31) in `GeoLite2-City.mmdb` from 2024-12-26.

Can you please confirm if

- this is intended but undocumented data type
or
- there was broken release that day (can you please check by resolving `146.19.120.10` IP against file from this day? I don't have historical file to verify it.)
?

**Comment by oschwald** [comment]
That is correct; there are no 16 byte floating point numbers.

As far as I know, there was not a broken release. Our libraries [also verify the size](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/484d8b7c9f28fe8a21e7b9940fb9ef615d5475e5/maxminddb/decoder.py#L59-L71). I expect that we would have received quite a few complaints if a corrupted file was somehow released. We also validate the files with [mmdbverify](https://github.com/maxmind/mmdbverify) as part of the release process.

Given the above, I am not sure what the cause would be. The report suggests that it is repeatable. Perhaps the file is becoming corrupted somehow during the download or when it is decompressed. You could check the SHA256 or MD5 hash of the file against what we publish.

**Comment by bbkr** [comment]
Thanks for prompt reply. Is there a way to download historical versions of `GeoLite2-City.mmdb` from your site along with SHA?
I'd like to run tests against my library while I'm waiting for issue reporter to upload his version of the file.

**Comment by oschwald** [comment]
You can download them on [this page](https://www.maxmind.com/en/accounts/current/geoip/downloads?show_all_dates=1).

**Comment by pheix** [comment]
After the update it works:

```
[kostas@webtech-omen ~]$ raku -MGeoIP2 -e 'GeoIP2.new( path => "/usr/share/GeoIP/GeoLite2-City.mmdb" ).locate(ip => "146.19.120.10")<country><iso_code>.say'
IEEE754 of size 16 not yet implemented. Sorry.
  in block  at /opt/rakudo/rakudo-star-2023.05/share/perl6/site/sources/E5A4B16713B62F06C1B07F86768C4F2791F78B68 (GeoIP2) line 361
  in method read-floating-number at /opt/rakudo/rakudo-star-2023.05/share/perl6/site/sources/E5A4B16713B62F06C1B07F86768C4F2791F78B68 (GeoIP2) line 357
  in method read-data at /opt/rakudo/rakudo-star-2023.05/share/perl6/site/sources/E5A4B16713B62F06C1B07F86768C4F2791F78B68 (GeoIP2) line 250
  in method read-metadata at /opt/rakudo/rakudo-star-2023.05/share/perl6/site/sources/E5A4B16713B62F06C1B07F86768C4F2791F78B68 (GeoIP2) line 154
  in submethod BUILD at /opt/rakudo/rakudo-star-2023.05/share/perl6/site/sources/E5A4B16713B62F06C1B07F86768C4F2791F78B68 (GeoIP2) line 35
  in block <unit> at -e line 1
[kostas@webtech-omen ~]$ geoipupdate -v
geoipupdate version 7.1.0 (662daf83, 2024-11-18T17:41:36Z, linux-amd64)
Using config file /etc/GeoIP.conf
Using database directory /usr/share/GeoIP
Initializing file lock at /usr/share/GeoIP/.geoipupdate.lock
Acquired lock file at /usr/share/GeoIP/.geoipupdate.lock
Calculated MD5 sum for /usr/share/GeoIP/GeoLite2-Country.mmdb: cfbfe1692194d89bccf433687f51c8b0
Updates available for GeoLite2-Country
Database GeoLite2-Country successfully updated: 4ce22566fa6dd97b54fea90f696bcd8d
Calculated MD5 sum for /usr/share/GeoIP/GeoLite2-City.mmdb: 2c33f97afeae3af1635cff9afe3a1074
Updates available for GeoLite2-City
Database GeoLite2-City successfully updated: 8a4f2cdbf8a8ee451a680a5bd2d356b4
Lock file /usr/share/GeoIP/.geoipupdate.lock successfully released
[kostas@webtech-omen ~]$ raku -MGeoIP2 -e 'GeoIP2.new( path => "/usr/share/GeoIP/GeoLite2-City.mmdb" ).locate(ip => "146.19.120.10")<country><iso_code>.say'
PL
[kostas@webtech-omen ~]$ raku -MGeoIP2 -e 'GeoIP2.new( path => "/usr/share/GeoIP/GeoLite2-Country.mmdb" ).locate(ip => "146.19.120.10")<country><iso_code>.say'
PL
[kostas@webtech-omen ~]$ 
```

Here's the gzipped version of the corrupted `GeoLite2-City.mmdb`: https://pheix.org/pub/GeoLite2-City.mmdb.gz

**Comment by bbkr** [comment]
I found the cause. It was faulty logic of locating metadata at the end of `mmdb` file in my module. In this specific case part of encoded metadata triggered detection too early, pointing to incorrect position in file. That is why decoder broke on random byte.

I'm very sorry about this confusion (file was not corrupted, it was my code to be blamed). I'm closing this issue , thanks for prompt replies and your help.

**Comment by oschwald** [comment]
No problem. I am glad you were able to figure it out.
