### ISSUE TITLE
Need clearer statement when NodeAddress equals NodeCount

### ISSUE THREAD

**Issue by Vidbuf** [maxmind/MaxMind-DB#20]
"The pointer can point to a value equal to $number_of_nodes."

Does this mean that the Pointer has a Value equal to the NodeCount?

Or does this mean that the location pointed to by this pointer will have a value equal to the NodeCount?

I'm guessing it's the former but the wording sounds more like the latter.

**Comment by autarch** [comment]
I'm going to remove this particular section since this described much more clearly under the "Search Lookup Algorithm" section a little bit further down in the docs.
