### ISSUE TITLE
Conflicting description of calculating address into data region

### ISSUE THREAD

**Issue by Vidbuf** [maxmind/MaxMind-DB#22]
The descriptions showing how to calculate addresses into the data section are in conflict and the example doesn't help (I think it's wrong).

$offset_in_file = ( $record_value - $node_count )
                  + $search_tree_size_in_bytes + 16

I think the above is correct, but it conflicts with the description below and the example given.

$data_section_offset = ( $record_value - $node_count ) - 16

The -16 should either be deleted, or it should be +16 if referenced from the end of the search tree.

**Comment by autarch** [comment]
Actually, it's the "+ 16" that's wrong. We had fixed that a while back but apparently forget to update the GitHub pages. Thanks!

**Comment by autarch** [comment]
Hmm, or maybe not. We'll discuss this a bit more internally.
