### ISSUE TITLE
IPv4 in 2001::/32 scope in GeoIP2-Country-Test.mmdb

### ISSUE THREAD

**Issue by J1bz** [maxmind/MaxMind-DB#27]
Hi,

I've run some dumping tests with GeoIP2-Country-Test.mmdb file. I was wondering why IPv4s are present in the 2001::/32 scope.

Let's take 67.43.156.0 for example. Following hexadecimal values are matched when iterating over the binary tree :
  - 0x432b9c00
  - 0xffff432b9c00
  - 0x20010000432b9c000000000000000000
  - 0x2002432b9c0000000000000000000000

As far as I know, IPv4 can be wrapped in ::/96, ::ffff:0:0/96 and 2002::/16 IPv6 scopes but it should not be so in 2001::/32. I'm not much at ease with IPv6 so maybe I'm missing something.

Thanks

**Comment by oschwald** [comment]
`2001::/32` is Teredo. Bits 32-63 is the IPv4 address of the Teredo server being used.
