### ISSUE TITLE
Diagram for 28 bit (medium db) discrepancy

### ISSUE THREAD

**Issue by jflatow** [maxmind/MaxMind-DB#3]
This doesn't seem like the right layout, they should be 2 big-endian unsigned ints, one after another right?

https://github.com/maxmind/MaxMind-DB/blob/master/MaxMind-DB-spec.md#28-bits-medium-database-one-node-is-7-bytes

The first int is shown with its higher order bits out of place.

**Comment by Vidbuf** [comment]
"Less obvious" is putting it nicely....
