### ISSUE TITLE
Maximum size of database metadata area is ambiguous

### ISSUE THREAD

**Issue by PatrickCronin** [maxmind/MaxMind-DB#32]
The [spec says](https://github.com/maxmind/MaxMind-DB/blame/master/MaxMind-DB-spec.md#L49) that the maximum size of the database metadata portion of the datafile is "128kb." Is that kilobits or kilobytes, and, is kilo measured as 10^3 or 2^10?

**Comment by alemax-xyz** [comment]
According to the source code it is 128 * 1024 = 131072 bytes

**Comment by PatrickCronin** [comment]
Did you find that [here in the DB Reader code](https://github.com/maxmind/MaxMind-DB-Reader-php/blob/master/src/MaxMind/Db/Reader.php#L19), or in a different place?

**Comment by oschwald** [comment]
This was intended to be kibibytes (2^10). The number was picked to be a multiple the kernel page size.

**Comment by oschwald** [comment]
This is fixed by #43.
