### ISSUE TITLE
Custom Key Values

### ISSUE THREAD

**Issue by thevirus20** [maxmind/MaxMind-DB#45]
Can I put any custom MD5 string as key and custom json structire as Value in MMdb?
Or is there any other way of achieve this in a mmdb file format?

**Comment by oschwald** [comment]
Sure, you can put any text you want in a string field.

**Comment by thevirus20** [comment]
Is it?
The program i used for creating mmdb in perl from here
https://blog.maxmind.com/2015/09/29/building-your-own-mmdb-database-for-fun-and-profit/

Gives error when I put anything other than ip/range as key.

Can you please guide me how can I achieve this.

Example:
`"some md5 string" -> {"json_key":"json_value"}`

**Comment by oschwald** [comment]
Sorry, I misunderstood. I thought you meant a key within the record. You could conceivably create a database with MD5 values in the tree as both MD5s and IPv6 addresses are 128-bit numbers, but you would likely be better off using SQLite or something similar.
