### ISSUE TITLE
golang reader support

### ISSUE THREAD

**Issue by thao6626** [maxmind/MaxMind-DB#48]
Hi:

Do you have plan to support golang reader for MMDB?

**Comment by oschwald** [comment]
I'd suggest looking at https://github.com/oschwald/geoip2-golang and https://github.com/oschwald/maxminddb-golang. We use them internally and they work well.

**Comment by thao6626** [comment]
I tried this yesterday, but there are some errors. I think the golang reader does not support the whole data format of the MMDB. 

The error log is :  
parse ip country error maxminddb: cannot unmarshal map into type []struct { GeoNameID uint "maxminddb:\"geoname_id\""; IsoCode string "maxminddb:\"iso_code\""; Names map[string]string "maxminddb:\"names\"" }

I see the source code of golang reader, the format of  City struct does not match the MMDB that I am using

**Comment by oschwald** [comment]
Please open an issue on that repo with the code you are using. The reader does support the full MMDB specification.
