### ISSUE TITLE
Does the production DB have some IPs which are guaranteed to return a particular value for different fields?

### ISSUE THREAD

**Issue by zero-master** [maxmind/MaxMind-DB#49]
Hey! we want to check the GEO data fields for a some IPs in our production integration test, it will help us guard again failed auto geoip db updates.

We are not interested in swapping out the production dbs. Is there a solution for us?

**Comment by oschwald** [comment]
Please email [support@maxmind.com](mailto:support@maxmind.com). They may be able to provide you with some IPs that are unlikely to change.
