### ISSUE TITLE
Please add "native" language to your databases.

### ISSUE THREAD

**Issue by bbkr** [maxmind/MaxMind-DB#53]
GeoIP2 databases introduced translations, but the fact that they are **forced** is really annoying.

Let's say I have a bunch of users with recognized IPs and I want to find users from Gdańsk, Kraków and Warszawa. Those from Gdańsk have english name "Gdańsk" - kinda counterintiutive because it is not an English word, but OK. Those from Kraków have english name "Krakow" - which makes things harder because "Cracow" is alternate spelling so I have to know which one was chosen in MM database. And those from Warszawa have english name translated to "Warsaw".

This makes creating any sane queries almost impossible. How the hell do I know if there is an English translation for Warząchewka or Szczebrzeszyn? And this goes both way - I want to show to Polish user that "Twój ostatni login był 2 dni temu z miasta _Warszawa_" (your last login was 2 days ago from Warsaw) not "Twój ostatni login był 2 dni temu z miasta _Warsaw_".

So my idea is to add native name next to returned languages, for example: 

```
    'subdivisions' => [
        {
            'geoname_id' => 3337496,
                'name' => 'Pomorskie',      <==== like this
                'names' => {
                'ru' => 'Поморское воеводство',
                'es' => 'Pomerania',
                'ja' => 'ポモージェ県',
                'de' => 'Woiwodschaft Pommern',
                'fr' => 'Voïvodie de Poméranie',
                'en' => 'Pomerania'
            },
            'iso_code' => 'PM'
        }
    ]
```

Is it possible?

Thanks!

**Comment by oschwald** [comment]
Thanks for the idea! We have discussed something like this previously but have not pursued it as we have always run into a few issues. In many countries, more than one language is spoken and the local name may differ in those different languages. We did consider using the official government names, but it is common for those names to be long and awkward and not what people actually use, e.g., "Commonwealth of Massachusetts" for "Massachusetts" in the United States. Also, we use GeoNames for our name data and, although they do have some flags around these things, we have not found that data to be consistent or very high quality.

**Comment by bbkr** [comment]
I agree, native names in multiple native languages will be a challenge to present in consistent manner. Maybe something like:

```perl
{
    'city' => {
        'names' => {
            'en' => 'Gdansk',
            'de' => 'Danzig',    # this is present if language is mentioned in metadata as translation
            'pl' => 'Gdańsk'    # this is additionally present if language is mentioned in result as official
        }
    },
    'official_languages' => [ 'pl' ] # would be a nice addition on its own
}
```

Or maybe just:
```perl
{
    'names' => { ...},
    'official_names' => {
        'pl' => 'Województwo pomorskie'
    }
}
```

So far I resolved this issue by using http://www.maxmind.com/GeoIPLocationCSV-localized.zip by geoname_id and correlated with list of official languages for each country. Yes, "official" names are weird, but querying it is far more easier than guessing english translation.

**Comment by bbkr** [comment]
Hi.

I've found that http://www.maxmind.com/GeoIPLocationCSV-localized.zip is missing. What is the new location of this file? Do you still support it?

**Comment by oschwald** [comment]
That file is no longer supported. It had not been updated in many years and was for use with the Legacy databases before GeoIP2 was released.

**Comment by bbkr** [comment]
It is very easy to tie `geoname_id` to data provided by GeoNames.org as I described here: https://github.com/bbkr/GeoIP2#translations

I think this task can be closed - there is no right way to do it in GeoIP database because there may be various interpretations of what "native" language is.
