### ISSUE TITLE
Gibberish text in ASN database

### ISSUE THREAD

**Issue by g-andrade** [maxmind/MaxMind-DB#59]
Hi,

I'm the maintainer of [locus](https://github.com/g-andrade/locus), an .mmdb reader library for Erlang. I've been working on a new analysis feature that looks for database corruption / incompatibilities (or bugs in my code instead.)

When I fed January 15th's GeoLite2 ASN database to this new analyzer, a single data record was rejected:
```erlang
* {data_record_decoding_failed,
      #{class => error,data_index => 1984015,
        reason =>
            {not_utf8_printable_text,
                <<67,104,105,110,97,32,116,101,108,101,99,111,109,32,195,131,
                  194,162,195,130,194,128,195,130,194,147,32,67,104,105,110,
                  97,32,78,101,120,116,32,71,101,110,101,114,97,116,105,111,
                  110,32,73,110,116,101,114,110,101,116>>},
        tree_prefix => {{8193,3176,0,0,0,0,0,0},32}}}
```

* The tree prefix is "2001:c68::/32" 
* The data record index is 1984015 (from the beginning of the data section)
* The string failing validation is "China telecom Ã¢ÂÂ China Next Generation Internet"

Alas, it _is_ valid UTF-8, and the spec doesn't say it has to be printable. But I found it strange, and hence I'd be thankful for your thoughts on this.

(And if possible, a definitive say on whether non-printable codepoint sequences like the one above are to be permitted.)

---
The mentioned database metadata:
```erlang
  #{<<"binary_format_major_version">> => 2,
    <<"binary_format_minor_version">> => 0,
    <<"build_epoch">> => 1547570011,
    <<"database_type">> => <<"GeoLite2-ASN">>,
    <<"description">> =>
        #{<<"en">> => <<"GeoLite2 ASN database">>},
    <<"ip_version">> => 6,
    <<"languages">> => [<<"en">>],
    <<"node_count">> => 720869,<<"record_size">> => 24},
```

**Comment by oschwald** [comment]
Thanks for raising this. It does look like that string got double encoded at some point.

As far as whether the databases can contain non-printable characters in UTF8 strings, this is allowed under the specification and a fully complaint decoder should handle it. That said, it seems unlikely that our GeoIP2/GeoLite2 databases would have such strings intentionally.

**Comment by oschwald** [comment]
The bad ASN data should be fixed in the February 5 release. Thanks again!
