### ISSUE TITLE
Recent tarballs unreadable by older tar implementations

### ISSUE THREAD

**Issue by g-andrade** [maxmind/MaxMind-DB#64]
(Not sure if this the appropriate place to report this.)

The numeric `uid`/`gid` of the files contained in the latest GeoLite2 database tarballs have changed from `2000` to `1991400094`[*].

This makes the tarballs incompatible with [older implementations](https://www.gnu.org/software/tar/manual/html_chapter/tar_8.html) of tar due to the new very large identifier. Sadly, the implementation [bundled with Erlang/OTP](http://erlang.org/documentation/doc-8.3/lib/stdlib-3.3/doc/html/erl_tar.html) up to version 19 is one of those, and my .mmdb reader is now [unable to load the latest tarballs](https://github.com/g-andrade/locus/issues/4) on not-so-old Erlang versions.

#### GeoLite2-Country.tar.gz (May 14th)
```
$ tar tvfz GeoLite2-Country.tar.gz --numeric-owner   
drwxr-xr-x 2000/2000         0 2019-05-13 19:20 GeoLite2-Country_20190514/
-rw-r--r-- 2000/2000        55 2019-05-13 19:20 GeoLite2-Country_20190514/COPYRIGHT.txt
-rw-r--r-- 2000/2000       433 2019-05-13 19:20 GeoLite2-Country_20190514/LICENSE.txt
-rw-r--r-- 2000/2000   3798346 2019-05-13 19:20 GeoLite2-Country_20190514/GeoLite2-Country.mmdb
```

#### GeoLite2-Country.tar.gz (May 21st)
```
$ tar tvfz GeoLite2-Country.tar.gz --numeric-owner   
drwxr-xr-x 1991400094/1991400094       0 2019-05-20 21:12 GeoLite2-Country_20190521/
-rw-r--r-- 1991400094/1991400094     433 2019-05-20 21:12 GeoLite2-Country_20190521/LICENSE.txt
-rw-r--r-- 1991400094/1991400094      55 2019-05-20 21:12 GeoLite2-Country_20190521/COPYRIGHT.txt
-rw-r--r-- 1991400094/1991400094 3769909 2019-05-20 21:12 GeoLite2-Country_20190521/GeoLite2-Country.mmdb
```

[*]: Username and group name remain the same: `tjmather`

**Comment by klp2** [comment]
Thanks for reporting this. I think that this will be corrected for next week's database releases, so I'm going to close this out. If you find that there are still issues after next week's databases are out, please let us know via support@maxmind.com.

**Comment by JBKahn** [comment]
This seems to have been fixed on the Country but not the City file.

**Comment by oschwald** [comment]
This should be resolved in this week's release.

**Comment by g-andrade** [comment]
I can confirm the issue I originally reported has been resolved for the GeoLite2 Country, City and ASN databases.

Thanks!
