### ISSUE TITLE
Source data doesn't match test data

### ISSUE THREAD

**Issue by g-andrade** [maxmind/MaxMind-DB#72]
In a specific case under [GeoIP2-Static-IP-Score-Test.json](https://github.com/maxmind/MaxMind-DB/blob/dcc5f97/source-data/GeoIP2-Static-IP-Score-Test.json#L148-L150), recently modified in order to [use floating point values](https://github.com/maxmind/MaxMind-DB/commit/44038b9ea3811592711ccd103a5b1425ed2577c9#diff-1cb38c5f7116f625c13108d54b843316), the JSON value `0.3` is corrupted when generating MMDB test data.

The problem is, `0.3` has no [**precise representation**](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) in binary floating point - its closest representable value is `2.99999999999999988898e-01`. But in this case, it's read as `0.30000000000000004` instead, which is the value to be found within `GeoIP2-Static-IP-Score-Test.mmdb`.

I boiled the issue down to what's (presumably) a bug in the [Cpanel::JSON::XS](https://metacpan.org/pod/Cpanel::JSON::XS) library, which is used to decode the JSON sources.

Here's a small perl script that reproduces the issue:
```perl
use Cpanel::JSON::XS qw( decode_json );

my $literal_float = 0.3;
my $json_object = decode_json('{"value": 0.3}');
my $json_float = $json_object->{value};

my $difference = $literal_float - $json_float;
print "$difference\n"
```
It outputs `-5.55111512312578e-17`. Mind. Blowing.

**Comment by oschwald** [comment]
Thanks for opening this and reporting it upstream! It should be fixed now.
