### ISSUE TITLE
Please rename Perl 6 to Raku on dev.maxmind.com

### ISSUE THREAD

**Issue by bbkr** [maxmind/MaxMind-DB#84]
Perl 6 was renamed to Raku in October 2019 and it is developed under its own brand since then.

I've noticed that on https://dev.maxmind.com/geoip/geoip2/downloadable/ module https://github.com/bbkr/GeoIP2 is listed as `Perl 6`. Please change description to `Raku`.

Thanks!

**Comment by oschwald** [comment]
Thanks! I've updated it.
