### ISSUE TITLE
Overlapping networks

### ISSUE THREAD

**Issue by rgr78** [maxmind/MaxMind-DB#87]
What is the expected behavior when there are (partially) overlapping subnets? Is it supported? What is returned in that case? All the matches? The smallest subnet?

Example, suppose we have 3 subnets:
10.0.0.0/8
10.1.0.0/16
10.1.1.0/24

When we query the IP 10.1.1.1, what is supposed to be returned? This IP belongs to all three networks.

Testing the current perl reader implementation, it is not clear what happens, it seems to vary.

**Comment by oschwald** [comment]
The format does not allow for overlapping subnets. It is a binary tree where only the leaf nodes have a data record associated with them.
