### ISSUE TITLE
Bad data that looks like it should be good data

### ISSUE THREAD

**Issue by g-andrade** [maxmind/MaxMind-DB#95]
Hi,

I've got this MMDB validation tool; I recently started running it over the `test-data/MaxMind-*.mmdb` test cases (as of comit 2bf1713) and encountered what looks like a few violations of the spec.

#### Under `test-data/MaxMind-DB-test-decoder.mmdb`

```erlang
{map_key_of_wrong_type_in_data_section,
   #{key => {uint32, 1},        
     position => 120,  % index from the start of the data section
     under => #{path => [{115,{map_with,12,elements}}]}}}
  ```
 * there's a map with 12 elements at index 115, and one of its keys (at index 120) is an `uint32` with value `1`
  
#### And under `test-data/MaxMind-DB-test-pointer-decoder.mmdb`

```erlang
{map_key_of_wrong_type_in_data_section,
   #{key => {uint32, 1},
     position => 9, % index from the start of the data section
     under => #{path => [{0,{map_with,15,elements}}]}}},
```
* there's a map with 15 elements at index 0, and one of its keys (at index 9) is an `uint32` with value `1`

```erlang
{map_key_of_wrong_type_in_data_section,
   #{key => {uint32, 7},
     position => 119,
     under =>
         #{path =>
               [{266,{map_with,12,elements}},
                {293,{pointer,108}},
                {108,{map_with,1,elements}},
                {114,{map_with,2,elements}}]}}}
```

* there's a map with 12 elements at index 266 and, after chasing a pointer, one of its values, which is another map at index 108 containing 1 element, contains yet another map itself, at index 114, with two elements, and one of the keys of the latter is an `uint32`, at index 119, with value `7`

---

The name of the tests suggested that nothing should be broken (it contains no words like "bad" or "broken"), but maybe I just assumed too much there.

Therefore, my questions are:
- Are they supposed to be broken,
- and if they're not, is the presence of those `uint32` map keys a bug?

As of the moment I'm not capturing the tree prefixes which lead to the erroneous data pieces (for performance reasons), which is why I'm only providing you with indices, but please tell me if that's not practical.

**Comment by oschwald** [comment]
Those databases should be valid. You can see what is in them in the [script that generates them](https://github.com/maxmind/MaxMind-DB/blob/2bf1713b3b5adcb022cf4bb77eb0689beaadcfef/test-data/write-test-data.pl#L183-L337). I haven't looked at the database in a hexeditor, but I did run our `mmdbverify` tool against them, which should return an error if there is a non-string key in a map.

Looking at the data inserted in the database, it looks like `1` and `7` show up in an array, not a map. Arrays can contain `uint32` values. Are you sure about the type of the container?

**Comment by oschwald** [comment]
I was thinking a bit more about this, and I was wondering if perhaps you are not taking into account the size of the array properly. Based on the description, it sounds like the array elements might be getting added into the map that contains the array rather than the array itself.

**Comment by g-andrade** [comment]
I'm sorry, I was debugging this and noticed that "MaxMind-DB-test-decoder.mmdb" and "MaxMind-DB-test-pointer-decoder.mmdb" were switched around (I've edited the first post to correct it.)

In any case: the parser can process those databases fine, so it's clearly an issue with the validator.

Nothing to see here.

Thanks! Sorry for the bother, I should have checked this first :upside_down_face:
